### PR TITLE
Support for adding custom classes to all icons

### PR DESCRIPTION
**Pull request by afzaalopera**
className prop added to all icons for adding custom classes when calling within react-components. For usage: e.g `<Search className="my-custom-class" />`

### CODE REVIEW

**Comment by Kilian** [comment]
Cool! Let me check it and I'll make a new release. It might take me a few days before I can get around to it.

**Comment by afzaalopera** [comment]
Sure take your time !  👍

**Comment by afzaalopera** [comment]
@Kilian any update on this ?

**Comment by Kilian** [comment]
Can you also update the README with the new optional prop className for all the icons? The code is good to go. If you can add the readme changes as well, I'll merge it in right away and make a new release.

**Comment by afzaalopera** [comment]
Done @Kilian

**Comment by Kilian** [comment]
here we go: https://www.npmjs.com/package/react-bytesize-icons Thanks @afzaalopera!

**Comment by afzaalopera** [comment]
Thank you @Kilian . This was actually my first experience committing publicly.

**Comment by Kilian** [comment]
Awesome! Good contribution. Sorry it took so long. Keep up the good work ;)

**Pull request merged**
